Adding support for multiple cluster management

diff --git a/opensaf/scripts/for-managing/cluster-destroy b/opensaf/scripts/for-managing/cluster-destroy
--- a/opensaf/scripts/for-managing/cluster-destroy
+++ b/opensaf/scripts/for-managing/cluster-destroy
@@ -1,60 +1,35 @@
 #!/bin/bash
+# Cluster management cluster
+# - destroy all cluster instances 
+
 clustername=default
 [[ ! -z $1 ]] && clustername=$1 
-SFS=/home/adrian/sharedfs/$clustername
-SCs=2
-PLs=200
+SFS=~/sharedfs/$clustername
 
-__create_container()
+__get_containers()
 {
-    echo "Destroying container $name"
-   
-    #if [ "$TIPC" = "yes" ]; then
-       PID=`docker inspect -f '{{.State.Pid}}' $1`
-       [[ $? -eq 0 ]] && ../../../bin/for-docker/tipc-namespace-teardown $PID
-    #fi
-    #perhaps graceful shutdown
-    docker stop $1
-    docker rm $1
+   docker ps -a | grep -o "${clustername}-[PS][LC]-[0-9]*" 
 }
 
-__create_scs()
+__destroy_containers()
 {
-	i=0
-	while [ $i -lt $SCs ]; do
-	   i=$(($i + 1))
-	   node=SC-$i 
-	   name=$clustername-SC-$i
-	   docker inspect $name > /dev/null 2>&1
-	   if [ $? -eq 0 ]; then 
-	     __create_container $name $node
-	     #docker-enter $node /home/opensaf/setup-opensaf-node
-	     #docker-enter $node /etc/init.d/opensafd stop
-	     #docker-enter $NODE /etc/init.d/opensafd start
-	   fi
-	done
+   for name in $@; do
+      echo -n "Destroying container $name..."
+      pid=`docker inspect -f '{{.State.Pid}}' $name`
+      [[ $pid -ne 0 ]] && ../../../bin/for-docker/tipc-namespace-teardown $pid
+      docker stop $name > /dev/null
+ 
+      # Finally delete the container
+      docker rm $name > /dev/null
+      if [ $? -eq 0 ]; then
+         echo "done"
+      else
+         echo "failed"
+      fi
+   done
 }
 
-__create_pls()
-{
-	i=2
-	while [ $i -lt $PLs ]; do
-	   i=$(($i + 1))
-	   node=PL-$i             
-	   name=$clustername-PL-$i
-	   docker inspect $name > /dev/null 2>&1
-	   if [ $? -eq 0 ]; then
-	     __create_container $name $node
-	   fi
-	done
-}
+__destroy_containers $(__get_containers)
 
-__create_scs 
-__create_pls
-exit 0
-docker-ps | grep " PL-" | cut -d "L" -f2 | cut -d " " -f1 | xargs -I {} bash -c "docker stop PL{} && docker rm PL{}"
-if [ "$1" = "all" ]; then
-  echo "Deleted also controllers"
-  docker-ps | grep " SC-" | cut -d "C" -f2 | cut -d " " -f1 | xargs -I {} bash -c "docker stop SC{} && docker rm SC{}"
-fi
-
+# delete the sharedfs
+rm -rf $SFS > /dev/null
